# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

    - name: Pull Docker image
      run: docker pull docker.pkg.github.com/oscaredv/boost-test/builder:20.04

    - name: Run Docker image and compile code
      run: |
        docker run --rm --name builder \
        -v $GITHUB_WORKSPACE:/boost-test \
        -w /boost-test \
        docker.pkg.github.com/oscaredv/boost-test/builder:20.04 \
        bash -c "mkdir -p build; cd build; cmake ..; make ; make coverage"
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: CoverageReport
        path: build/coverage

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/coverage # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch

    - name: Coverage report
      uses: vebr/jest-lcov-reporter@v0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./build/tests.info
  
#    - name: Coverage report
#      uses: devmasx/coverage-check-action@v1.1.0
#      with:
#        type: lcov
#        result_path: ./build/tests.info
#        min_coverage: 90
#        token: ${{secrets.GITHUB_TOKEN}}

#    - name: Coverage report
#      uses: ambimax/action-report-coverage@add-support-for-push-event
      #uses: romeovs/lcov-reporter-action@v0.2.11
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        lcov-file: ./build/tests.info
  
