name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  DOCKER_IMAGE: docker.pkg.github.com/brunvoll-group/brucon5/builder-ubuntu:20.04

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

    - name: Pull Docker image
      run: docker pull $DOCKER_IMAGE

    - name: Run Docker image and compile code
      run: |
        docker run --rm --name builder \
        -v $GITHUB_WORKSPACE:/brucon5 \
        -w /brucon5 \
        $DOCKER_IMAGE \
        bash -c "mkdir -p build; cd build; cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON; make ; make test"
